<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Prontuario.API</RootNamespace>
    <UserSecretsId>prontuario-api-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update=".env">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Prontuario.Domain\Prontuario.Domain.csproj" />
    <ProjectReference Include="..\Prontuario.Application\Prontuario.Application.csproj" />
    <ProjectReference Include="..\Prontuario.Infrastructure\Prontuario.Infrastructure.csproj" />
  </ItemGroup>

</Project>
